# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Krystian Kuzyk
tagline:          'Computer Programmer/Analyst'
description:      'Computer Programmer/Analyst'
url:              https://freezebreath.github.io
baseurl:          /

author:
  name:           'Krystian Kuzyk'
  url:            https://freezebreath.github.io

paginate:         5
paginate_path:    "/blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/freezebreath/freezebreath.github.io

social:
  twitter:        https://twitter.com/freezebreath
  google:         https://plus.google.com/+freezebreath
  linkedin:       https://www.linkedin.com/in/krystian-kuzyk-30151897/
